<?php
require('top.inc.php');

if(isset($_POST['str'])){
    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();
    $str=$_POST['str'];
    curl_setopt($ch, CURLOPT_URL, 'https://api.openai.com/v1/chat/completions');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    $postdata=array(
        "model"=> "text-davinci-001",
        "prompt"=>$str,
        "messages"=> [],
        "temperature"=> 1,
        "max_tokens"=> 256,
        "top_p"=> 1,
        "frequency_penalty"=> 0,
        "presence_penalty"=> 0 );
    $postdata=json_encode($postdata);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $postdata);

    $headers = array();
    $headers[] = 'Content-Type: application/json';
    $headers[] = 'Authorization: Bearer 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';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
    $result = json_decode($result, true);
    //echo "<pre>";
    print_r($result);
    //echo $result['choices'][0]['text'];
}
?>
<div class="content pb-0">
            <div class="animated fadeIn">
               <div class="row">
                  <div class="col-lg-12">
                     <div class="card">
                        <div class="card-header"><strong></strong><small> </small></div>
                        <form method="post" enctype="multipart/form-data">
							<div class="card-body card-block">
                                <h1>ChatGPT Tool</h1>
								
								<div class="form-group">
									<input type="hidden" name="name" value="doremon-converter" placeholder="Enter product name" class="form-control" required>
								</div>
								
								<div class="form-group">
									<label for="categories" class=" form-control-label">Ask Chat GPT</label>
									<input type="text" name="str" class="form-control">
								</div>
								
								
								
							   <button id="payment-button" name="submit" type="submit" class="btn btn-lg btn-info btn-block">
							   <span id="payment-button-amount">Submit</span>
							   </button>
							   <div class="field_error"></div>
							</div>
						</form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         
<?php
require('footer.inc.php');
?>